Try to make perfect BEM No1
htmlacademy-adaptive/2051093-mishka-26 pull request #2
Opened 2022-07-27 20:18 UTC by AnnaLuna111

2022-07-28 11:08 UTC, firefoxic commented on source/index.html
> +		<h3 class="product-block__subtitle">Товар недели</h3>
В аутлайне заголовков весь идущий далее контент секции проваливается в подчинение этому подзаголовку.
И как-то это многовато для этой надписи.
Это скорее не подзаголовок, а какая-то временная метка на товаре, текст которой может быть «новинка», «хит продаж» и тд.

2022-07-28 13:36 UTC, firefoxic requested changes

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +		<h3 class="product-block__subtitle">Товар недели</h3>
В аутлайне заголовков весь идущий далее контент секции проваливается в подчинение этому подзаголовку. И как-то это многовато для этой надписи. Это скорее не подзаголовок, а какая-то временная метка на товаре, текст которой может быть «новинка», «хит продаж» и тд.

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +			<dd class="product-block__description">15 см</dd>
Тут наверное не очень подходит слово `description`, скорее `value`. Да и `parameter` можно сократить до `key`. В спеке так и пишут про этот список, что он для любых пар данных типа «ключ/значение» :)

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +				<cite class="review__author"><b>Анастасия Красильникова</b>@misssssiskras</cite>
Тег `<cite>` не для указания в нём автора цитаты. Он для указания названия источника цитаты (книги, статьи, и тд).

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +			</blockquote>
В теге `<blockquote>` не должно быть ничего лишнего. Только текст цитаты. Набор вложенных тегов и вообще структура могут быть какими угодно из допустимых внутри потокового элемента. Но контентом должен бы текст самой цитаты и ничего больше. Автора там точно быть не должно, иначе его имя в текст цитаты включается.

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +				</label>
Группу радиокнопок хорошо бы объединять в филдсет с легендой. При сложностях стилизации этих капризулек можно будет заменить их дивами с aria-атрибутами (или сразу так сделать, один див уже есть, надо лишь для легенды добавить).

Ну и значений у полей не хватает 😉

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +		<button class="contacts__button button">Напишите нам</button>
А что произойдёт при нажатии на кнопку? 🤔

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +		<button class="review__button button" type="button">Написать</button>
И тут тоже: что произойдёт при нажатии?

2022-07-28 13:36 UTC, firefoxic commented on source/index.html
> +		<button class="product-block__button button" type="button">Заказать</button>
И здесь: какое действие при нажатии? 🤭

2022-07-28 13:36 UTC, firefoxic commented on source/templates/footer.twig
> +			<img src="#"  alt="Логотип HTML-Академии.">
Хоть это и логотип, но тут он не контентный. Контентный только логотип самого сайта, а не его разработчика/дизайнера/etc. Примерно как в случае с ссылками на профили в соцсетях. Тут тоже достаточно текста в доступно скрытом спане.

2022-07-28 13:36 UTC, firefoxic commented on source/templates/header.twig
> +	<a class="header__logo logo" href="../index.html">
В разметке пути к сожалению надо писать не как редактор подсказывает, а исходя из того, где как итоговые файлы располагаться внутри `build/`, поэтому в этих путях до страниц с самих страниц надо убрать одну точку.

Кстати, в стилях я это поведение пофиксил вам — там как редактор подсказывает, так и ставим пути, а плагинчик их исправляет на рабочие 🙃

2022-07-28 13:36 UTC, firefoxic commented on source/catalog.html
> +					<div class="product__container-small">
А можешь пояснить, что значит `container-small`?

2022-07-28 13:36 UTC, firefoxic commented on source/catalog.html
> +						</button>
Тот же вопрос про действие кнопки)

2022-07-28 13:36 UTC, firefoxic commented on source/catalog.html
> +			<video class="production__video" src="#"></video>
Тег `video` не понадобится. Тут просто превью картинкой, поверх которой кнопкоссылка на видео, по клику на которую скрипт отменяет переход и вставляет вместо этого виджета видос с ютуба (скрипт писать не надо).

2022-07-28 13:36 UTC, firefoxic commented on source/form.html
> +		<h2 class="visually-hidden">Форма заказа</h2>
Что-то как-то избыточно. Достаточно одного заголовка. И всё это в одной секции.

2022-07-28 13:36 UTC, firefoxic commented on source/form.html
> +						</label>
Опять у радиокнопок значения потерялись :)

2022-07-28 13:36 UTC, firefoxic commented on source/form.html
> +						</label>
Чекбоксам, когда они в одной группе (про одно и то же), как и радиокнопкам тоже лучше задавать одинаковый `name` и разные `value`. Тогда на сервер будет отправляться не кучка разрозненных названий чекбоксов, а один массив, именованный по `name` и содержащий только отмеченные чекбоксы. Это удобнее обрабатывать.

2022-07-28 13:36 UTC, firefoxic commented on source/form.html
> +					<input class="form__filter-input" name="surname" type="text" placeholder="Укажите фамилию*">
У обязательных полей отсутствует `required`.

2022-07-28 13:36 UTC, firefoxic commented on source/form.html
> +			</fieldset>
Ко всем полям ввода должны прилагаться их лейблы, которые должны содержать текст.
А вот если поле одно — то это уже как-то не набор полей, не set of fields… ну то есть не fieldset 😉

2022-07-31 11:28 UTC, AnnaLuna111 commented on source/index.html
> +			<dd class="product-block__description">15 см</dd>
сделано)

2022-07-31 11:31 UTC, AnnaLuna111 commented on source/index.html
> +		<h3 class="product-block__subtitle">Товар недели</h3>
исправила  заголовок на span, и подкорректировала класс

2022-07-31 11:42 UTC, AnnaLuna111 commented on source/index.html
> +				<cite class="review__author"><b>Анастасия Красильникова</b>@misssssiskras</cite>
изменила див на список, вынесла <cite> из цитаты

2022-07-31 11:57 UTC, AnnaLuna111 commented on source/index.html
> +		<button class="contacts__button button">Напишите нам</button>
намек поняла, исправила на ссылку

2022-07-31 11:57 UTC, AnnaLuna111 commented on source/index.html
> +		<button class="review__button button" type="button">Написать</button>
тут тоже ссылка

2022-07-31 12:01 UTC, AnnaLuna111 commented on source/templates/footer.twig
> +			<img src="#"  alt="Логотип HTML-Академии.">
поняла

2022-07-31 12:04 UTC, AnnaLuna111 commented on source/catalog.html
> +					<div class="product__container-small">
маленький контейнер в большом😅
поняла, что не подходит, на тот момент фантазия сломалась

2022-07-31 12:14 UTC, AnnaLuna111 commented on source/catalog.html
> +			<video class="production__video" src="#"></video>
пока что убрала

2022-07-31 12:14 UTC, AnnaLuna111 commented on source/form.html
> +		<h2 class="visually-hidden">Форма заказа</h2>
переделала одну секцию на див

2022-07-31 12:17 UTC, AnnaLuna111 commented on source/catalog.html
> +						</button>
тип потерялся, да, 
исходя из прошлого проекта это были кнопки: те добавляешь в корзину продукт, но не преходишь по ссылке каждый раз, когда нажимаешь на кнопку, а только при оформлении заказа

2022-07-31 12:27 UTC, AnnaLuna111 commented on source/form.html
> +						</label>
сделано

2022-07-31 12:28 UTC, AnnaLuna111 commented on source/form.html
> +					<input class="form__filter-input" name="surname" type="text" placeholder="Укажите фамилию*">
пока не ставила, чтобы не мешал стилизовать потом, если критично, то могу сейчас поставить

2022-07-31 13:37 UTC, firefoxic commented on source/index.html
> +				<cite class="review__author"><b>Анастасия Красильникова</b>@misssssiskras</cite>
Хорошо, что вынесла. Только это про другое замечание 👀
Это про то, что `<cite>` для указания не автора цитаты, а цитируемого произведения. Тут нет произведения (книги или статьи), только автор отзыва. И этого автора надо просто текстом оставить после `<blockquote>`. А если хочется, чтобы была связь автора с его отзывом, можно обернуть автора в `<figcaption>` и всё это вместе с отзывом обернуть в `<figure>`.

2022-07-31 13:40 UTC, firefoxic commented on source/catalog.html
> +					<div class="product__container-small">
Ок, потом обсудим, как улучшить 🙂

2022-07-31 13:43 UTC, firefoxic commented on source/catalog.html
> +						</button>
Давай таки заменим на ссылки, раз уж решили 👀

2022-07-31 13:51 UTC, firefoxic commented on source/catalog.html
> +				<!--тут могло быть ваше видео-->>
Могло быть видео, но появился лишний символ `>` 😅

2022-07-31 14:09 UTC, firefoxic commented on source/templates/footer.twig
> +			<span class="visually-hidden">Логотип HTML-Академии.</span>
Фраза какой-то ломаной получается:
> Разработано _Логотип HTML-Академии_.

Было бы лучше как-то так:
>Разработано _в HTML-Академии_

Кстати, точка тут не обязательна 👀

2022-07-31 14:29 UTC, firefoxic commented on source/form.html
> +					<span class="visually-hidden">Пожелания</span>
А где же лэйбл?)
И скрытую дописку можно прямо в заг… в лейбл добавить:

```suggestion
					<label class="form__filter-title">Доп<span class="visually-hidden">олнительные пожелания:</span></label>
```
Только про `for` не забудь, и `id` у `textarea` 👀

2022-07-31 14:36 UTC, firefoxic commented on source/form.html
> +				</fieldset>
Лэйблы появились — хорошо. Но филдсеты с легендами тут лишние.
Просто удаляем их и добавляем дивы для стилизации:
```suggestion
				<div class="form__filter-group">
					<label class="form__filter-title">Тел
						<input class="form__filter-input" name="phone" type="tel" placeholder="+7 ХХХ ХХХ ХХ ХХ*">
					</label>
				</div>
				<div class="form__filter-group">
					<label class="form__filter-title">E-mail
						<input class="form__filter-input" name="email" type="email" placeholder="Ваш Email*">
					</label>
				</div>
```

2022-07-31 14:57 UTC, AnnaLuna111 commented on source/form.html
> +				</fieldset>
не доглядела, исправила

2022-08-02 11:17 UTC, merged